### ISSUE TITLE
Documentation: How does one prevent puppeteer from being downloaded when `yarn install` or `npm install` runs?

### ISSUE THREAD

**Issue by rudolfbyker** [cenfun/puppeteer-chromium-resolver#1]
This looks like a nice module, but the docs are a bit cryptic. It would be good to explicitly show how one can prevent puppeteer from being downloaded the old way when `yarn install` or `npm install` runs.

**Comment by cenfun** [comment]
good question, will add more details

**Comment by rudolfbyker** [comment]
Do I understand correctly that one needs to remove `puppeteer` from their project's dependencies, and then use `puppeteer-core` which is provided by `puppeteer-chromium-resolver`?

**Comment by cenfun** [comment]
not really,  the only differences between puppeteer-core and puppeteer are:
puppeteer-core doesn't automatically download Chromium when installed.
see https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteer-vs-puppeteer-core
puppeteer-chromium-resolver download Chromium to user custom path and cacheable, sometimes we could remove node_modules but do NOT want to download Chromium again, and we should share Chromium to multiple projects, does NOT download Chromium to each node_modules.

**Comment by rudolfbyker** [comment]
What I meant was: If I have another package that depends on puppeteer
directly, then that package will still download Chromium, even though I
have a direct dependency on puppeteer-chromium-resolver. Is that correct?
If so, then I need to remove the other package that depends directly on
puppeteer, since I need to prevent the automatic download of Chromium.

Or is there another way?

**Comment by cenfun** [comment]
Yes, you should repleace puppeteer with puppeteer-chromium-resolver. They are repeated
Do NOT list "puppeteer" or "puppeteer-core" in dependencies if exist "puppeteer-chromium-resolver".
 puppeteer-chromium-resolver can't stop other puppeteer download Chromium automatically

**Comment by rudolfbyker** [comment]
My problem was that I depend on package `X`, which depends on `puppeteer`, but I also need to use `puppeteer` directly through `puppeteer-chromium-resolver`. I tried this solution:

In `package.json`:

```json
  "resolutions": {
    "puppeteer": "https://registry.npmjs.org/puppeteer-chromium-resolver/-/puppeteer-chromium-resolver-4.0.0.tgz"
  }
```

Then when I run `yarn install`, it uses `puppeteer-chromium-resolver` as a *replacement for* `puppeteer`. In the generated `yarn.lock`:

```json
puppeteer@^1.7.0, "puppeteer@https://registry.npmjs.org/puppeteer-chromium-resolver/-/puppeteer-chromium-resolver-4.0.0.tgz":
  version "4.0.0"
  resolved "https://registry.npmjs.org/puppeteer-chromium-resolver/-/puppeteer-chromium-resolver-4.0.0.tgz#be7ad1b29d109f00f0255447c809b49755f26976"
  dependencies:
    gauge "^3.0.0"
    object-assign "^4.1.1"
    ping-monitor "^0.4.4"
    puppeteer-core "^4.0.1"
```

Then just to check, I ran `rm -rf node_modules && yarn install` again. It was quick, and didn't download Chromium again.

That seems good, but the code doesn't run properly, because when module `X` tries to `require("puppeteer")`, it actually gets `PCR` instead of `puppeteer`. I think I will have to write a glue code module that depends on `puppeteer-chromium-resolver` and use that to replace `puppeteer`, or maybe even patch this `puppeteer-chromium-resolver` to allow it to function as a drop-in replacement for `puppeteer`. That would be very useful.

**Comment by cenfun** [comment]
@rudolfbyker  I got it. Could you please try following global ENV "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" to skip download?
https://github.com/puppeteer/puppeteer/blob/main/install.js#L34-L79
list in package.json config: https://docs.npmjs.com/configuring-npm/package-json#config
and the next step is set executable path "PUPPETEER_EXECUTABLE_PATH" to PCR.executablePath
`process.env.PUPPETEER_EXECUTABLE_PATH = PCR.executablePath;`
see Environment Variables here: https://github.com/puppeteer/puppeteer/blob/v5.0.0/docs/api.md#environment-variables

**Comment by cenfun** [comment]
1, add config "puppeteer_skip_download = true" to .npmrc
2, set env PUPPETEER_EXECUTABLE_PATH to PCR executablePath
Usage:
```
const PCR = require("puppeteer-chromium-resolver");
const puppeteer = require("puppeteer");
const main = async()=>{
    const pcr = await PCR();
    process.env.PUPPETEER_EXECUTABLE_PATH = pcr.executablePath
    const browser = await puppeteer.launch({
        headless: false
    });
    const page = await browser.newPage();
    await page.goto('https://github.com');
    await browser.close();
}
main();
```

**Comment by rudolfbyker** [comment]
> Could you please try following global ENV "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" to skip download?

Thanks, I already did that. But it doesn't solve the problem, because the dependency of my module still needs Chromium to be downloaded at some point.

> the next step is set executable path "PUPPETEER_EXECUTABLE_PATH" to PCR.executablePath
> `process.env.PUPPETEER_EXECUTABLE_PATH = PCR.executablePath;`

This is a step in the right direction, but it will only work if you can cause that line to run before anything else that might need puppeteer.

**Comment by cenfun** [comment]
## How to make puppeteer work with puppeteer-chromium-resolver
* 1, prevent the automatic download of Chromium: add config "puppeteer_skip_download = true" to .npmrc (or yarn config)
* 2, set env PUPPETEER_EXECUTABLE_PATH to PCR executablePath before calling puppeteer.launch()

I have tried above steps and it works.

**Comment by rudolfbyker** [comment]
Like I said, I totally agree that it will work. But only if you have control over when `puppeteer.launch` is called. That is not always the case, especially when puppeteer is not a direct dependency of your project.

**Comment by cenfun** [comment]
so your puppeteer running in main process or an unknown child process?
it seems difficult to set env for child process, but easy for main process.

**Comment by rudolfbyker** [comment]
Node is single threaded, and so is JS in the browser, so there are no child processes. I'm talking about the situation where you use a module that depends on puppeteer, without having puppeteer in your direct dependencies.

**Comment by cenfun** [comment]
I understand your situation.
do you have a entry js file to start your node process? you should set PUPPETEER_EXECUTABLE_PATH at the very beginning of entry file.
const moduleA = require("module-a");
const moduleB = require("module-b"); //if puppeteer exist in module-b
process.env.PUPPETEER_EXECUTABLE_PATH = PCR.executablePath; //set env here before execute module-b
moduleB();
do you have a chance to control this?

**Comment by rudolfbyker** [comment]
Thanks for your helpful comments and suggestions.

> do you have a chance to control this?

Not really. Puppeteer is executed when running `vue-cli-service build`. My dependency tree to puppeteer looks like this:

`myproject` → `vue-cli-plugin-prerender-spa` → `prerender-spa-plugin` → `@prerenderer` → `renderer-puppeteer` → `puppeteer`

> add config "puppeteer_skip_download = true" to .npmrc

When I set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true on the command line, it works, but setting it in .npmrc or .yarnrc has no effect, even though it should. I'm not sure why...

```
$ yarn config list
yarn config v1.22.4
info yarn config
{
  ...
  puppeteer_skip_download: true
}
info npm config
{
  ...
  puppeteer_skip_download: true
}
```

For now, I'm using the code as in my pull request, which works for my project.

**Comment by cenfun** [comment]
The root cause is the puppeteer version you installed was v2.x, try adding both puppeteer_skip_download = true and PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = true to .npmrc

Thanks for your pr, I will do some reasearch on vue-cli-plugin-prerender-spa ...

**Comment by cenfun** [comment]
close
