### ISSUE TITLE
yarn install hangs indefinitely

### ISSUE THREAD

**Issue by matbeedotcom** [cenfun/puppeteer-chromium-resolver#11]
Node:16, Yarn: 3
install.js hangs indefinitely on my Docker setup. On my host Windows/Mac, no problem. I had to patch install.js to process.exit(0) at PCR().then(() -> process.exit)

**Comment by cenfun** [comment]
install.js will be execute automatically when yarn or npm install. could you please try different versions of yarn2 or npm to see if works?

**Comment by cenfun** [comment]
could you please update new version puppeteer-chromium-resolver@19.3.1 and try again?
