### ISSUE TITLE
Support puppeteer-extra and plugins

### ISSUE THREAD

**Issue by megaacheyounes** [cenfun/puppeteer-chromium-resolver#12]
Hi, How can I make this package work with [puppeteer-extra](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra) and add plugins like [stealth-plugin](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth) and [adblocker](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-adblocker)
can you add typescript types :)

**Comment by megaacheyounes** [comment]
my current solution
```typescript
import puppeteerExt from 'puppeteer-extra';

import StealthPlugin from 'puppeteer-extra-plugin-stealth';
puppeteer.use(StealthPlugin());

import AdblockerPlugin from 'puppeteer-extra-plugin-adblocker';
puppeteer.use(AdblockerPlugin({ blockTrackers: true }));

import PCR from 'puppeteer-chromium-resolver';

const stats = await PCR(options);
debug('stats', stats);

browser = await puppeteerExt
    .launch({
      headless: false,
      executablePath: stats.executablePath,
    })
    .catch((err: any) => debug('initBrowser failed', err));

```

**Comment by cenfun** [comment]
it seems that `puppeteer-extra` combined the `puppeteer`, so no way to work with `PCR` unless `puppeteer-extra` be adapted to `PCR`
https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra/rollup.config.ts#L23
