### ISSUE TITLE
uncompactable chromium version is installed by PCR causing issue in puppeter

### ISSUE THREAD

**Issue by natraj-ng-17587** [cenfun/puppeteer-chromium-resolver#13]
Error: spawn UNKNOWN\n    at ChildProcess.spawn (node:internal/child_process:413:11)\n    at Object.spawn (node:child_process:700:9)\n    at Object.spawn (pkg/prelude/bootstrap.js:2076:27)\n    at new Process (C:\\snapshot\\node_fies\\node_modules\\@puppeteer\\browsers\\lib\\cjs\\launch.js:103:56)\n    at launch (C:\\snapshot\\node_fies\\node_modules\\@puppeteer\\browsers\\lib\\cjs\\launch.js:50:12)\n    at ChromeLauncher.launch (C:\\snapshot\\node_fies\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\node\\ProductLauncher.js:76:54)\n    at async C:\\snapshot\\node_fies\\index.js:150:25
[
![Screenshot from 2024-06-10 20-32-13](https://github.com/cenfun/puppeteer-chromium-resolver/assets/96224813/46af229d-93f1-4382-9272-76b4ee65e684)
](url)

kindly fix this issue

**Comment by cenfun** [comment]
Can you try remove the downloaded chromium package and reinstall again?
the download dir could be `{homedir()}/.chromium-browser-snapshots`, for example: `C:\Users\{user-name}\.chromium-browser-snapshots`

**Comment by natraj-ng-17587** [comment]
tried getting the same issue when I try to open the chromium I am getting this
![Screenshot from 2024-06-11 10-45-55](https://github.com/cenfun/puppeteer-chromium-resolver/assets/96224813/b2571c0d-729d-4be7-9a9d-e9cd32ba90f7)

**Comment by cenfun** [comment]
I thought that it is a issue of puppeteer or chromium on your PC, but not puppeteer-chromium-resolver. `puppeteer-chromium-resolver` just download  puppeteer and chromium to your PC. 
Could you please report this to puppeteer: https://github.com/puppeteer/puppeteer/issues
or see https://pptr.dev/troubleshooting
