### ISSUE TITLE
Move puppeteer-core to peerDeps

### ISSUE THREAD

**Issue by Armanio** [cenfun/puppeteer-chromium-resolver#14]
Hi!
Thx for very useful package! Very handy

My proposal: move puppeteer-core to [peerDependencies](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#peerdependencies)? PCR work like a pluggable plugin in host codebase and host must have puppeteer(-core) thats why PCR dont need puppeteer in own package list. 
Discuss please.

PS: sorry for my terrible english, feel free to correct me

**Comment by cenfun** [comment]
When installing PCR, we try starting Chromium to see if it can start successfully. At this point, it requires to run Puppeteer, which is why `puppeteer-core` is in the dependencies.
What issue did this cause in your situation? Why move it to `peerDependencies` from `dependencies`?

**Comment by Armanio** [comment]
Thx for you respond!
Yes i understand why you need `puppeteer-core` in you codebase, but i think `puppeteer-core` its not direct dependency for PCR like `gauge` or other deps.
If `puppeteer-core` will be moved to `peerDependencies` user (plugin consumer) can control `puppeteer` version on own codebase: for example i use `puppeteer@22.12.0`

**Comment by cenfun** [comment]
Like I said, `puppeteer-core` is a PCR dependency and it has been used for checking Chromium if `launchable`, see
https://github.com/cenfun/puppeteer-chromium-resolver/blob/master/lib/index.js#L5

I understand you want to control `puppeteer` version, but if you are using `puppeteer` then there is no need to use `PCR` anymore, `puppeteer` will finish installtion by self. This is why `PCR` just depends on `puppeteer-core` but not `puppeteer`.

any thought?

**Comment by Armanio** [comment]
Oh i understood. It seems that you right and i could be drop puppeteer from own deps and use puppeteer from PCR stats.
