### ISSUE TITLE
mac npm install puppeteer-chromium-resolver@23.0.0 fail

### ISSUE THREAD

**Issue by Z-feiyao** [cenfun/puppeteer-chromium-resolver#15]
os：mac pro m1
When I use `npm install puppeteer-chromium-resolver` to install it, an error is reported:

<img width="824" alt="image" src="https://github.com/user-attachments/assets/27e268e2-5952-4e1f-a458-04393d25b98d" />

**Comment by cenfun** [comment]
Just test it, it seems to work well
https://github.com/cenfun/puppeteer-chromium-resolver/actions/runs/12468752727/job/34800559357
