### ISSUE TITLE
Licensing: Missing details

### ISSUE THREAD

**Issue by Baenlin** [cenfun/puppeteer-chromium-resolver#5]
Hello,
I would like to include this package in some company project. But we are only allowed to include packages if details of the licence are available.

Could the owner of the project provide this details, please?

How to add this license:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by cenfun** [comment]
added.
https://github.com/cenfun/puppeteer-chromium-resolver/blob/master/LICENSE
let me know if you have any questions

**Comment by Baenlin** [comment]
Thank you.
