### ISSUE TITLE
Running on docker container / AWS elastic bean creates access denied for read write .stats.json. EACCES: permission denied

### ISSUE THREAD

**Issue by anujmv** [cenfun/puppeteer-chromium-resolver#7]
Thank you for the library.

In aws manually going into linux environment and changing permission temporarily fixes the issue. however for every deployment the permission changes back to root for this particular file. Is there a solution to this.

In docker it fails to completed chrome download UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/home/<usernam>/app/node_modules/puppeteer-chromium-resolver/.stats.json' while trying with a user

However if no USER set in docker, if run as root no issues.

Is there a way to create .stats.json with out setting permission as root?

**Comment by cenfun** [comment]
please try following
update your local version to puppeteer-chromium-resolver@19.1.0 
```
//package.json
"dependencies": {
    "puppeteer-chromium-resolver": "^19.1.0" 
```
just moved .stats.json to user home dir, should have permission?  
see https://github.com/cenfun/puppeteer-chromium-resolver/blob/master/lib/index.js#L414-L418  
or, edit permission in Dockerfile
```
...
RUN chmod 777 -R /your-workspace-dir
...
```
Hope this helps, if you have any questions please let me know

**Comment by anujmv** [comment]
Its working now on docker when build in windows and also aws elastic beanstalk. Thank you.

M1 mac has some issues when trying to docker build and run of linux/arm64, chrome/chromium is unable to launch. Since issue not related to this library closing this. Thank you once again
