### ISSUE TITLE
Change the installation folder path from ".chromium-browser-snapshots" to X path

### ISSUE THREAD

**Issue by CarlosLunaGit** [cenfun/puppeteer-chromium-resolver#9]
Hello, I am trying to use this library within a Docker Container that sets some restricted access to some folders. Thus the default path that is used ".chromium-browser-snapshots" within the **options** object is not accessible.

Causing this error:

> [PCR] Error: EACCES: permission denied, mkdir '/.chromium-browser-snapshots'

I wonder if we can add some lines to make this code identify if the user of this library wants to modify the path, while also identifying of the new path is a relative or an absolute one. 

By doing so, in my case now I will be able to use this library and specify at will to use the `~/tmp` folder at my linux server for downloading chrome and the other stuff since the tmp folder is open for me to write on it.

looking add the code I propose the following changes:

Options object gets a new property "homeDirBased" of type Boolean:

```  
const option = {
      revision: "",
      detectionPath: "",
      folderName: "./crtest/.chromium-browser-snapshots",
      homeDirBased: false,
      defaultHosts: ["https://storage.googleapis.com", "https://npm.taobao.org/mirrors"],
      hosts: [],
      cacheRevisions: 2,
      retry: 3,
      silent: false
  };
  const stats = await PCR(option);
```

then at index.js file:
New condition added "option.folderName === '.chromium-browser-snapshots'"
```
const PCR = async (option = {}) => {

    option = getOption(option);

    //from stats cache
    outputSilent = true;
    const stats = getStats();
HERE---------------->// new condition added to identify default path change
    if (stats && fs.existsSync(stats.executablePath) && option.folderName === '.chromium-browser-snapshots') {
        //if has custom revision should be matched
        if (!option.revision || (option.revision && option.revision === stats.revision)) {
            return stats;
        }
    }

    //try to detection and install
    outputSilent = option.silent;

    option.puppeteerConf = initPuppeteerConf(option);
    option.revision = initRevision(option);
    output(`Chromium revision: ${EC.magenta(option.revision)}`);
    option.userFolder = initUserFolder(option);
    //output("User folder: " + option.userFolder);

    const localChromium = detectionLocalChromium(option);
    if (!localChromium) {
        await downloadHandler(option);
        await launchHandler(option);
    }

    const revisionInfo = await revisionHandler(option);
    //console.log(revisionInfo);

    saveStats(revisionInfo);

    //close gauge
    gauge.disable();

    return revisionInfo;
};
```
Then initUserFolder function gets a new conditional that checks homeDirBased
homeDirBased = true,  means user wants to resolve the path by using the home Dir
homeDirBased = means it wont merge the home Dir,  it will take the raw input and resolve it, leaving the user with the choice of using either relative or absolute paths at choice.

```
const initUserFolder = (option) => {

    const homePath = os.homedir();

HERE---------------->// new conditional on homeDirBased option
    let userFolder = '';
    if (option.homeDirBased) {
        userFolder = path.resolve(homePath, option.folderName);
    }else{

        userFolder = path.resolve(option.folderName);
    }
    
    if (fs.existsSync(userFolder)) {
        return userFolder;
    }
    try {
        fs.mkdirSync(userFolder, '0777');
        // Make double sure we have 0777 permissions; some operating systems
        // default umask does not allow write by default.
        fs.chmodSync(userFolder, '0777');
    } catch (e) {
        output(`User path is not writable: ${userFolder}`);
        output(e);
    }
    return userFolder;
};
```
Thanks.

**Comment by cenfun** [comment]
Today I made some code refactoring and added one more option "downloadPath" for your case.
Please have a try:
1, install new version puppeteer-chromium-resolver@^19.2.0
2, using option downloadPath like
```js
const stats = await PCR({
  downloadPath: '.temp'
});
```
if you have any feedback please let me know, thanks.
